version: '3'

services:
  web:
    build:
      context: .
      dockerfile:
    env_file:
      - .env
    command: ["sh", "server.sh"]
    ports:
    - 8000:8000

  postgres:
    image: postgres:12
    ports:
    - 5432:5432
