version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/project
    env_file:
      - .env
    command: ["sh", "server.sh"]
    ports:
    - 80:8000

  postgres:
    image: postgres:12
    ports:
    - 5432:5432
    volumes:
      - local_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=deliveries

volumes:
  local_db:
